# -*- coding: utf-8 -*-
"""
Convert GuaDatabase_V3.0.json into a JS constant file loadable via <script>.

Why: in the pure H5 (file://) build, fetch('GuaDatabase_V3.0.json') is blocked
by CORS, so the detail data is inlined as a global and consumed by
gua-data-json.js instead.

Usage: python build_h5_data.py
"""

import json
from pathlib import Path

BASE = Path(__file__).parent
SRC = BASE / 'GuaDatabase_V3.0.json'
DST = BASE / 'GuaDatabase_V3.0.data.js'

HEADER = """/**
 * GuaDatabase_V3.0 inlined data (for the pure HTML5 / offline build).
 *
 * AUTO-GENERATED by build_h5_data.py -- do not edit by hand.
 * Exposes window.GUA_DATABASE_V3; gua-data-json.js prefers it over fetch(),
 * which bypasses the CORS restriction on file:// URLs.
 */
"""


def main() -> None:
    data = json.loads(SRC.read_text(encoding='utf-8'))
    if not isinstance(data, list) or not data:
        raise SystemExit('Invalid source JSON: expected a non-empty array')

    payload = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    DST.write_text(HEADER + 'window.GUA_DATABASE_V3 = ' + payload + ';\n', encoding='utf-8')

    print('Wrote %s: %d gua, %.0f KB' % (DST.name, len(data), DST.stat().st_size / 1024))


if __name__ == '__main__':
    main()
